<?php
$titulo = &$titulo;
$urlData = &$urlData;
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?= $titulo?></title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/jquery/bootgrid/jquery.bootgrid.css">
        <link rel="stylesheet" href="/bootstrap/font-awesome/css/all.css">

        <script src="/jquery/jquery.js" ></script>
        <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="/jquery/bootgrid/jquery.bootgrid.js" ></script>
        <script src="/jquery/bootgrid/jquery.bootgrid.fa.js" ></script>
    </head>
    <body>
    <div class="container-fluid">
        <div class="col-2">&nbsp;</div>
        <div class="col-8">
            <h1 class="-align-center"><?= $titulo?></h1>
            <table id="grid-data-api" class="table table-condensed table-hover table-striped" >
                <thead>
                <tr>
                    <th data-column-id="id" data-type="numeric" data-identifier="true">ID</th>
                    <th data-column-id="name">Nombre</th>
                    <th data-column-id="link"  data-formatter="link" data-order="desc">Link</th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="col-2">&nbsp;</div>
    </div>
    <script>
        $("#grid-data-api").bootgrid({
            ajaxSettings: {
                method: "GET",
                cache: false
            },
            ajax: true,
            url: "<?= $urlData?>",
            selection: true,
            multiSelect: true,
            rowSelect: true,
            keepSelection: true,
            formatters: {
                "link": function(column, row)
                {
                    return "<a href='" + row.id + "'><i class='fa fa-edit'></i></a>";
                },
                "commands": function(column, row)
                {
                    return "<button type=\"button\" class=\"btn btn-xs btn-default command-edit\" data-row-id=\"" + row.id + "\"><span class=\"fa fa-pencil\"></span></button> " +
                        "<button type=\"button\" class=\"btn btn-xs btn-default command-delete\" data-row-id=\"" + row.id + "\"><span class=\"fa fa-trash-o\"></span></button>";
                }
            },
            labels: {
                all: "Todos",
                infos: " {{ctx.start}} a {{ctx.end}} de {{ctx.total}} registros",
                loading: "Cargando...",
                noResults: "No hay resultados!",
                refresh: "Actualizar",
                search: "Buscar"
            }
        });
    </script>
    </body>
</html>
